name: News Collection Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  collect-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Check HF token
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          if [ -n "$HF_TOKEN" ]; then
            echo "HF_TOKEN is available"
          else
            echo "HF_TOKEN is NOT available"
            exit 1
          fi
      - name: Collect news
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python main.py
